
==  Projektantrag
=== Projektziele
Das Ziel des Projektes ist eine fertige Webseite zu haben, mit der man die Roboter kontrollieren kann und eine Software die es ermöglicht mit Input Geräten den Roboter zu Steuern. Außerdem wird es möglich sein die Steuerung anzupassen und das wird in einer Datenbank gespeichert.

=== Projektumfang:

- Webseite
- Erkennen Von Input Geräten
- Software die Inpute an Server sendet
- Software um Einstellungen zu verändern
- Kommunikation mit Renn-Server
- Datenbank und Server

=== Projektzeitplan:

1. Webseite mit QR Codes | 7 - 14. Tage
2. Entwicklung der Input Geräte Erkennung | 3 - 8 Tage
3. Kommunikation mit Server | 2 - 5 Tag
4. Senden der Empfangenen Inputs an den Server | 3 - 5 Tage
5. Implementierung des Servers zum Speichern der Einstellungen der Nutzer | 10 Tage
6. Test und Optimierung | 1 - 4 Tage

=== Ressourcenbedarf:
- Controller
- Matte
- Test Hardware

=== Entwicklungsteam:

- Tobias Richter
- Andreas Hasenschwandtner

=== Finanzielle Ressourcen:
- 0

=== Projektabschluss:
Das Projekt wird abgeschlossen, sobald die definierten Ziele erreicht sind und die Softwarelösung erfolgreich getestet und implementiert wurde.
